name: Sync upstream repo

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3AM UTC
  workflow_dispatch:     # Allows you to trigger manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "Avtarkis"
          git config --global user.email "avtarkiscareers@gmail.com"

      - name: Add Upstream and Sync
        run: |
          git remote add upstream https://github.com/MoonshotAI/Kimi-K2.git
          git fetch upstream
          git checkout main
          git merge upstream/main || echo "Already up to date"
          git push origin main
